[2022-08-29 09:25:13,226] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.clean_data scheduled__2022-08-29T09:09:45.805061+00:00 [queued]>
[2022-08-29 09:25:13,231] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.clean_data scheduled__2022-08-29T09:09:45.805061+00:00 [queued]>
[2022-08-29 09:25:13,231] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 09:25:13,231] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-29 09:25:13,231] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 09:25:13,247] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): clean_data> on 2022-08-29 09:09:45.805061+00:00
[2022-08-29 09:25:13,251] {standard_task_runner.py:52} INFO - Started process 13420 to run task
[2022-08-29 09:25:13,255] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_data', 'clean_data', 'scheduled__2022-08-29T09:09:45.805061+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/model_dag.py', '--cfg-path', '/tmp/tmpnqdnba9g', '--error-file', '/tmp/tmpjihdb85h']
[2022-08-29 09:25:13,255] {standard_task_runner.py:80} INFO - Job 52: Subtask clean_data
[2022-08-29 09:25:13,306] {task_command.py:371} INFO - Running <TaskInstance: preprocessing_data.clean_data scheduled__2022-08-29T09:09:45.805061+00:00 [running]> on host rc1b-dataproc-m-xzxwmqcudfo0foh0.mdb.yandexcloud.net
[2022-08-29 09:25:13,349] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=preprocessing_data
AIRFLOW_CTX_TASK_ID=clean_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T09:09:45.805061+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T09:09:45.805061+00:00
[2022-08-29 09:25:13,350] {pyspark_cleaning.py:19} INFO - 
[2022-08-29 09:25:13,350] {client.py:192} INFO - Instantiated <Client(url='http://rc1b-dataproc-m-xzxwmqcudfo0foh0.mdb.yandexcloud.net:9870')>.
[2022-08-29 09:25:13,351] {client.py:305} INFO - Fetching content summary for '/user/airflow/input_files'.
[2022-08-29 09:25:34,551] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/fraud-detection-ml/utils/pyspark_cleaning.py", line 77, in clean_data
    VectorAssembler().setInputCols(["TX_FRAUD"]).setOutputCol(["TX_FRAUD_Vectorized"])
AttributeError: 'VectorAssembler' object has no attribute 'setOutputCols'
[2022-08-29 09:25:34,556] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=preprocessing_data, task_id=clean_data, execution_date=20220829T090945, start_date=20220829T092513, end_date=20220829T092534
[2022-08-29 09:25:34,571] {standard_task_runner.py:92} ERROR - Failed to execute job 52 for task clean_data ('VectorAssembler' object has no attribute 'setOutputCols'; 13420)
[2022-08-29 09:25:34,589] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-29 09:25:34,612] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
