[2022-09-16 13:44:52,319] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.validate_model scheduled__2022-09-16T13:23:50.286208+00:00 [queued]>
[2022-09-16 13:44:52,324] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.validate_model scheduled__2022-09-16T13:23:50.286208+00:00 [queued]>
[2022-09-16 13:44:52,324] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-16 13:44:52,324] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-09-16 13:44:52,324] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-16 13:44:52,343] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): validate_model> on 2022-09-16 13:23:50.286208+00:00
[2022-09-16 13:44:52,350] {standard_task_runner.py:52} INFO - Started process 68137 to run task
[2022-09-16 13:44:52,355] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_data', 'validate_model', 'scheduled__2022-09-16T13:23:50.286208+00:00', '--job-id', '369', '--raw', '--subdir', 'DAGS_FOLDER/model_dag.py', '--cfg-path', '/tmp/tmpdy2frfv9', '--error-file', '/tmp/tmp72iz66wz']
[2022-09-16 13:44:52,355] {standard_task_runner.py:80} INFO - Job 369: Subtask validate_model
[2022-09-16 13:44:52,405] {task_command.py:371} INFO - Running <TaskInstance: preprocessing_data.validate_model scheduled__2022-09-16T13:23:50.286208+00:00 [running]> on host rc1b-dataproc-m-xzxwmqcudfo0foh0.mdb.yandexcloud.net
[2022-09-16 13:44:52,465] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=preprocessing_data
AIRFLOW_CTX_TASK_ID=validate_model
AIRFLOW_CTX_EXECUTION_DATE=2022-09-16T13:23:50.286208+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-16T13:23:50.286208+00:00
[2022-09-16 13:45:08,202] {logging_mixin.py:115} WARNING - 2022/09/16 13:45:08 INFO mlflow.spark: 'runs:/427a7ec9d11f4e29895906f71d20fbfc/model' resolved as 's3://otus-bigdata-dima-ioksha/1/427a7ec9d11f4e29895906f71d20fbfc/artifacts/model'
[2022-09-16 13:45:08,286] {credentials.py:1094} INFO - Found credentials in environment variables.
[2022-09-16 13:45:08,944] {logging_mixin.py:115} WARNING - 2022/09/16 13:45:08 INFO mlflow.spark: URI 's3://otus-bigdata-dima-ioksha/1/427a7ec9d11f4e29895906f71d20fbfc/artifacts/model/sparkml' does not point to the current DFS.
[2022-09-16 13:45:08,944] {logging_mixin.py:115} WARNING - 2022/09/16 13:45:08 INFO mlflow.spark: File 's3://otus-bigdata-dima-ioksha/1/427a7ec9d11f4e29895906f71d20fbfc/artifacts/model/sparkml' not found on DFS. Will attempt to upload the file.
[2022-09-16 13:45:10,502] {logging_mixin.py:115} WARNING - 2022/09/16 13:45:10 INFO mlflow.spark: Copied SparkML model to /tmp/mlflow/7f23f1ae-6a8a-4a08-b920-6a59c0027744
[2022-09-16 13:45:17,908] {logging_mixin.py:115} WARNING - 2022/09/16 13:45:17 INFO mlflow.spark: 'runs:/427a7ec9d11f4e29895906f71d20fbfc/pipeline' resolved as 's3://otus-bigdata-dima-ioksha/1/427a7ec9d11f4e29895906f71d20fbfc/artifacts/pipeline'
[2022-09-16 13:45:19,310] {logging_mixin.py:115} WARNING - 2022/09/16 13:45:19 INFO mlflow.spark: URI 's3://otus-bigdata-dima-ioksha/1/427a7ec9d11f4e29895906f71d20fbfc/artifacts/pipeline/sparkml' does not point to the current DFS.
[2022-09-16 13:45:19,310] {logging_mixin.py:115} WARNING - 2022/09/16 13:45:19 INFO mlflow.spark: File 's3://otus-bigdata-dima-ioksha/1/427a7ec9d11f4e29895906f71d20fbfc/artifacts/pipeline/sparkml' not found on DFS. Will attempt to upload the file.
[2022-09-16 13:45:20,357] {logging_mixin.py:115} WARNING - 2022/09/16 13:45:20 INFO mlflow.spark: Copied SparkML model to /tmp/mlflow/1880d667-e658-4fa3-90ac-6c11e5d8cd05
[2022-09-16 13:47:58,502] {validate_model.py:47} INFO - POINT ESTIMATION OF F1 IS 0.0
[2022-09-16 13:47:59,235] {logging_mixin.py:115} WARNING - 2022/09/16 13:47:59 INFO mlflow.spark: 'models:/fraud-transaction-predictor/Production' resolved as 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/model'
[2022-09-16 13:47:59,721] {logging_mixin.py:115} WARNING - 2022/09/16 13:47:59 INFO mlflow.spark: URI 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/model/sparkml' does not point to the current DFS.
[2022-09-16 13:47:59,721] {logging_mixin.py:115} WARNING - 2022/09/16 13:47:59 INFO mlflow.spark: File 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/model/sparkml' not found on DFS. Will attempt to upload the file.
[2022-09-16 13:48:00,527] {logging_mixin.py:115} WARNING - 2022/09/16 13:48:00 INFO mlflow.spark: Copied SparkML model to /tmp/mlflow/c5deb982-43dd-4c24-9207-c7caa4b8befc
[2022-09-16 13:48:01,868] {logging_mixin.py:115} WARNING - 2022/09/16 13:48:01 INFO mlflow.spark: 'models:/fraud-transaction-pipeline/Production' resolved as 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/pipeline'
[2022-09-16 13:48:02,392] {logging_mixin.py:115} WARNING - 2022/09/16 13:48:02 INFO mlflow.spark: URI 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/pipeline/sparkml' does not point to the current DFS.
[2022-09-16 13:48:02,392] {logging_mixin.py:115} WARNING - 2022/09/16 13:48:02 INFO mlflow.spark: File 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/pipeline/sparkml' not found on DFS. Will attempt to upload the file.
[2022-09-16 13:48:03,440] {logging_mixin.py:115} WARNING - 2022/09/16 13:48:03 INFO mlflow.spark: Copied SparkML model to /tmp/mlflow/621a0d19-6657-4bae-a0f5-190961b596a6
[2022-09-16 13:50:41,733] {validate_model.py:47} INFO - POINT ESTIMATION OF F1 IS 0.0
[2022-09-16 13:50:42,251] {validate_model.py:97} INFO - Mean 0.0 and std of considering model 0.0
[2022-09-16 13:50:42,251] {validate_model.py:98} INFO - Mean 0.0 and std of best model 0.0
[2022-09-16 13:50:42,251] {validate_model.py:119} INFO - NEW MODEL IS WORSE THEN THE PRODUCTION
[2022-09-16 13:50:42,252] {python.py:173} INFO - Done. Returned value was: None
[2022-09-16 13:50:42,258] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=preprocessing_data, task_id=validate_model, execution_date=20220916T132350, start_date=20220916T134452, end_date=20220916T135042
[2022-09-16 13:50:42,312] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-16 13:50:42,324] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
